### ISSUE TITLE
Document common sites

### ISSUE THREAD

**Issue by jacobisaliveandwell** [hkgumbs/multi#14]
Tried out Slack today, but my notifications don't seem to be working with a minimal config. Might be cool to document the successful configs somewhere.

**Comment by jacobisaliveandwell** [comment]
It looks like notification issues are related to the way the site determines my "away" status. I wonder if there is anything that can be done about this. Does it warrant another issue?

**Comment by hkgumbs** [comment]
First, thanks for checking Multi! Slack is actually the main Multi app that I've been using on a daily basis, and notifications seem to work for me. I tested your theory about the "away" status by using `/remind me to walk in 1 minute` and putting the app in the background. Multi still sent the notification, which makes me think the problem is elsewhere.

One thing I noticed in the documentation is that by default macOS does not show notifications is the app is in the foreground. I wonder if that's what you're noticing. If that's not it, then maybe we could run a little test. Could you create a test app with the following JSON config:

```json
{ "tabs": [{ "title" :"Notifications Test", "url" :"https://www.bennish.net/web-notifications.html" }] }
```

That will open to a simple notification test site. From there you can click "Show in 5s" then background the app. That will give us a baseline as to whether notifications aren't working for some reason or it's something off with Slack.

**Comment by jacobisaliveandwell** [comment]
Interesting. Indeed. It looks like the way MacOS handles focus, one must have focus on another window.

It be really cool to start building out knobs for things like always showing messages. Either way, thanks for this project. Moving to mac from linux has been extremely painful and this makes it a little better.

**Comment by hkgumbs** [comment]
I like the idea to make this into a configuration option. Just implemented that and published a new release! If you install with the new `.dmg` (which should replace your previous installation), then you'll have access to a new flag called `alwaysNotify`. Hope that helps your transition to macOS!!

Release: https://github.com/hkgumbs/multi/releases/tag/v2.0.1
Documentation: https://github.com/hkgumbs/multi/tree/2.x#json-configuration

**Comment by ericboehs** [comment]
I'm also not getting notifications on 10.15.7 (Safari 14.0). I tried the web-notifications.html app and nothing happens. If I click Authorize button it says permission is granted but I can't get it to notify me even if I do "Show me in 5s" and then de-focus the app.

I'm also not seeing it in Notifications.prefPane.

---
I've looked at other third-party Slack clients and I think Multi will be the best solution as it'll give full Slack feature set while enabling accessibility features (I use Shortcat to navigate macOS with the keyboard).
