### ISSUE TITLE
Ability to add custom CSS (and maybe JS?)

### ISSUE THREAD

**Issue by EricAndrechek** [hkgumbs/multi#19]
Hi, first off I wanted to say I **LOVE** this app, I think I know have a problem as every website I use regularly has been turned into a multi-app. The problem with this, however, is any extensions I had no longer work inside multi. My example use case would be I am using a website I don't want to sign in on and I can use this website without signing in just fine, there's just always a part of the webpage taken up telling me to sign-in. In Chrome I made a simple extension to just run some CSS on that specific domain to hide that banner, but in Multi I am not seeing a way this is possible. I think that would be an amazing feature too and would be something you could edit in the JSON configuration. 

On a similar note, I think the ability to add your own javascript into the Multi app would be fantastic (another feature an extension could accomplish). This way I could have JS implemented to do things like translate text and such. Maybe I am overly optimistic about this project, but I am envisioning a sort of plugin store for multi where you could package and install extensions to run.

Lastly, I didn't see anywhere to donate to this (I would try to contribute to this project with code but I know nothing about Swift apps and such, so a monetary donation is the next best thing). Do you have a Paypal link or OpenCollective fund you would consider adding to the readme?

Thanks!

**Comment by hkgumbs** [comment]
Hey Eric, thanks a bunch for the encouragement!! I _really_ like the idea of a directory of common script and style injections! I want to think a bit more about the specifics like where it's hosted and how it's updated—I'll post an update in a few days.

Re: donating, Multi is actually setup with a licensing model. One week after you start using it you'll see a message asking you to purchase a license. It's optional, and you can keep using the app either way, but that's how I plan to support new features and fixes. You could purchase the license early if you wanted, so that when the message pops up you'd have a code ready. Here's the direct link if you want to go that route: https://gumbs.llc/multi/

**Comment by hkgumbs** [comment]
Following up from last week, I think I'll just start with a document in the repository that includes CSS snippets that other folks have found helpful. If there's enough interest, I still think it'd be cool to "graduate" it to a package manager kinda thing.I'll update this issue once I have the feature and document ready, then maybe you could add the snippets you've found helpful.

**Comment by EricAndrechek** [comment]
Sounds great! Excited to try it, and I will for sure add some CSS snippets I found helpful when I get the chance to test them out in multi.

**Comment by hkgumbs** [comment]
This is released in https://github.com/hkgumbs/multi/releases/tag/v2.0.4. I added documentation and simple examples at https://github.com/hkgumbs/multi/blob/2.x/Documentation/CUSTOM-CSS.md. Looking forward to see what you send over!
