### ISSUE TITLE
Feature request: closing the window without quitting the application

### ISSUE THREAD

**Issue by Etheryte** [hkgumbs/multi#6]
Most Mac applications allow you to close the application window, but keep the application running. By default, this can be done either by <kbd>cmd</kbd><kbd>W</kbd> or the red cross in the top-left corner. Clicking on the application icon on the dock would open a new window after the fact.  

With the recent [handy addition of the minimize command](https://github.com/hkgumbs/multi/commit/c381ad9959ac43045e480da4bfe2f9b53b40edf5), this would complete the set of basic OS-level shortcuts you would usually find in a native application.  

Currently, the feature set is partially covered:

- [x] The window should close from the red cross button
- [ ] The window should close on <kbd>cmd</kbd><kbd>W</kbd>
- [ ] A new window should be opened when there are no windows and the application icon is clicked

It might be worth considering hiding the window instead of closing it, allowing the application to continue receiving notifications without having a user-facing window open.

**Comment by hkgumbs** [comment]
Thanks for the idea—just looked into it. Like you said, I don't think we can keep notifications working if the window is closed. macOS already has Hide and Minimize features, which I've implemented and do keep notifications working. The fact that the red cross closes the window with no way to re-open is a bug, which is addressed in https://github.com/hkgumbs/multi/commit/5cea07f73fa1e11a45f96b930deb6dc335c80e5b

Another thing which makes me hesitate, is that I'd like to start using proper macOS tabs (#7) instead of hijacking the main window each time. Looking into this issue prompted me to look further into that actually! Tabs would give a few more macOS-native shortcuts, like `^Tab` to cycle to the next.

All that to say, if I implement `⌘W` to alias Hide or Minimize, that would be even more confusing for people used to tabs. I agree that it should probably do _something_ though. I'm just not sure what the most natural thing is. Maybe it closes the tab, but the whole point of this app is to have "persistent" websites. Maybe it just closes the app after a confirmation dialog... What do you think?

**Comment by Etheryte** [comment]
That's good insight, thanks for explaining your side. I looked at a few other applications to get a feel for what's some common approaches to this:  

 - Safari, Chrome etc close tabs until there's one left, pressing <kbd>cmd</kbd><kbd>W</kbd> on the last one closes the window but keeps the application running.  
 - iTerm2, VSCode etc perform the same way when tabs are enabled.  
 - Slack doesn't have tabs, but has threads and other toggleable sections, pressing <kbd>cmd</kbd><kbd>W</kbd> is identical to <kbd>cmd</kbd><kbd>H</kbd>: the window's internal state is untouched, the window is simply hidden.
 - Discord performs identical to Slack.  

Given persistent tabs is the core feature Multi offers, mimicking what Slack and Discord do seems like a good option: the application layout is unchanged, <kbd>cmd</kbd><kbd>W</kbd> is the same as <kbd>cmd</kbd><kbd>H</kbd>. <kbd>cmd</kbd><kbd>Q</kbd> can be used to quit.

**Comment by hkgumbs** [comment]
Thanks for doing that research! I pushed a change which sets `Cmd-W` to Hide the window (identical to `Cmd-H`). You can update your apps by `git pull`-ing the changes then running `./create-mac-app APP_NAME ICON_PATH --update`

**Comment by Etheryte** [comment]
Thanks a lot for your work and time, works like a charm. 👍
